const mongoose = require('mongoose');

const usersSchema = new mongoose.Schema({
    
    uid: String, // gotten from google oauth or generated by us
    name: String, // Name, can be retrieved from google oauth sign in, or created by user on account create page
    email: String, // Email, can be retrieved from google oauth sign in, or created by user on account create page
    password: String, // password from bcrypt if the user creates an account without signing in from google | will be empty if google sign-in

    badges: [{ // array of badges the user will have displayed on their profile - ID will correspond to badge object
        badgeId: String,
    },],

    allergies: [{ // array of allergies the user will have displayed on their profile - ID will correspond to allergy object
        allergyId: String,
    },],

    pantries: [{ // array of allergies the user will have attached to their profile - ID will correspond to pantry object
        pantryId: String,
    },],

    friends: [{ // array of friends the user will have attached to their profile - ID will correspond to user object
        uid: String,
    },],

});

const Users = mongoose.model('Users', usersSchema);

module.exports = Users;